Reverting `export *` syntax (#2597)
Reverting `export *` syntax because it is breaking module augmentation for `FastifyReply`

For example, the following code fails:

```
import fastify from 'fastify';

declare module 'fastify' {
  interface FastifyReply {
    hello: string;
  }
}

const server = fastfiy();
server.decorateReply('hello', 'world');

server.get('/hello', async (request, reply) => {
  reply.send(reply.hello);
})
```
with error: `Property 'hello' does not exist on type 'FastifyReply<Server, IncomingMessage, ServerResponse, RouteGenericInterface, unknown>'.`

And after applying the fix, the code works as expected and returns `world`.